all:
  children:
    masters:
      hosts:
        192.168.1.100:
        192.168.1.101:
        192.168.1.102:
      vars:
        control_network: 192.168.2.0/24
    nodes:
      hosts:
        192.168.1.103:
      vars:
        control_network: 192.168.2.0/24
  vars:
    ansible_user: root
    ansible_ssh_pass: contrail123
