all:
  children:
    masters:
      hosts:
        35.229.121.133:
        34.73.75.246:
        35.196.33.217:
    nodes:
      hosts:
        35.196.220.212:
        35.243.198.96:
  vars:
    ansible_user: mhenkel
    ansible_ssh_private_key_file: /Users/mhenkel/.ssh/google_compute_engine
    ansible_become: true
