all:
  children:
    masters:
      hosts:
        35.243.198.96:
    nodes:
      hosts:
        35.229.121.133:
  vars:
    ansible_user: mhenkel
    ansible_ssh_private_key_file: /Users/mhenkel/.ssh/google_compute_engine
    ansible_become: true
